# Generated by Django 5.2.15 on 2026-06-08 19:29

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0032_category_exclude_from_menu_category_long_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_label', models.CharField(max_length=40)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True, help_text='HTML/markdown body (demo). Production may attach a PDF.')),
                ('min_crest', models.PositiveSmallIntegerField(default=2, help_text='Minimum crest count to read (default 2 = Patron).')),
                ('published', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='ProgramConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_threshold', models.DecimalField(decimal_places=2, default=Decimal('25000.00'), help_text='Lifetime spend (USD) that earns the 3rd crest — Collector.', max_digits=12)),
                ('curator_threshold', models.DecimalField(decimal_places=2, default=Decimal('75000.00'), help_text='Lifetime spend (USD) that earns the 4th crest — Curator.', max_digits=12)),
                ('steward_threshold', models.DecimalField(decimal_places=2, default=Decimal('200000.00'), help_text='Lifetime spend (USD) that earns the 5th crest — Steward (also reachable by invitation).', max_digits=12)),
                ('credit_accrual_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0200'), help_text="Retailer's Credit accrued per purchase, as a fraction of spend (e.g. 0.02 = 2%). Applies to Collector+ purchases.", max_digits=5)),
            ],
            options={
                'verbose_name': 'Program configuration',
                'verbose_name_plural': 'Program configuration',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive accrues credit; negative redeems/reduces it.', max_digits=12)),
                ('type', models.CharField(choices=[('accrued', 'Accrued'), ('redeemed', 'Redeemed'), ('adjusted', 'Adjusted')], default='accrued', max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DemoPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_purchases', to='catalogue.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EarlyAccessListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_to_min_crest', models.PositiveSmallIntegerField(default=4, help_text='Minimum crest count that can see this first (e.g. 4 = Curator).')),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('window_end', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_access', to='catalogue.product')),
            ],
            options={
                'ordering': ['-window_start'],
            },
        ),
        migrations.CreateModel(
            name='GrailEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=120)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('matched', 'Matched')], default='watching', max_length=10)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grail_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grail entry',
                'verbose_name_plural': 'Grail entries',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('accepted', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_issued', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(default='Member', max_length=20)),
                ('crest_count', models.PositiveSmallIntegerField(default=0)),
                ('lifetime_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('invited', models.BooleanField(default=False, help_text='Invited to Steward, independent of spend.')),
                ('concierge_channel', models.CharField(choices=[('none', 'No concierge'), ('email', 'Email concierge'), ('dedicated', 'Dedicated channel'), ('direct', 'Direct line')], default='none', max_length=12)),
                ('alerts_email', models.BooleanField(default=True)),
                ('alerts_sms', models.BooleanField(default=False)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-lifetime_spend'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('first_look', 'First look'), ('grail_match', 'Grail match'), ('restock', 'Restock'), ('price', 'Price alert'), ('program', 'Program')], default='program', max_length=12)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(blank=True, max_length=400)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
