# Generated by Django 5.2.15 on 2026-06-09 03:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0006_auto_20200724_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('feed_url', models.URLField(blank=True)),
                ('feed_format', models.CharField(default='xml', max_length=12)),
                ('feed_enabled', models.BooleanField(default=False)),
                ('auto_sync', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('last_sync_result', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to='partner.partner')),
            ],
            options={
                'verbose_name': 'Merchant profile',
            },
        ),
    ]
