# Generated by Django 5.2.15 on 2026-06-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketvalue',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original retail / list price, for the premium-to-retail figure.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='marketvalue',
            name='value_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
