# Generated by Django 5.2.15 on 2026-07-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Referenced by {% ad_zone 'slug' %}.", unique=True)),
                ('name', models.CharField(max_length=80)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('target_url', models.CharField(default='/advertise/', help_text='Where the placeholder creative links.', max_length=300)),
                ('placeholder_image', models.CharField(blank=True, help_text='Static path to the placeholder creative (auto-set by lifestyle_ads).', max_length=200)),
                ('revive_tag', models.TextField(blank=True, help_text='Revive Adserver invocation code. Used instead of the placeholder when settings.REVIVE_ENABLED is True.')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ad zone',
                'ordering': ['slug'],
            },
        ),
    ]
