# Generated by Django 5.2.15 on 2026-07-11 20:02

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_category_exclude_from_menu_category_long_description'),
        ('lifestyle', '0002_adzone'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Authors index',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('post_type', models.CharField(choices=[('standard', 'Standard Article'), ('feature', 'Long-form Feature'), ('gallery', 'Photo Gallery'), ('video', 'Video Feature'), ('interview', 'Interview / Profile'), ('review', 'Review'), ('guide', 'Guide / How-To'), ('event', 'Event Coverage'), ('list', 'Curated List')], default='standard', help_text='Pick the kind of story — drives layout, schema and badge.', max_length=16)),
                ('subtitle', models.CharField(blank=True, help_text='Dek / standfirst.', max_length=255)),
                ('hero_alt_text', models.CharField(blank=True, help_text='Required when a hero image is set.', max_length=255)),
                ('hero_caption', models.CharField(blank=True, max_length=255)),
                ('hero_credit', models.CharField(blank=True, max_length=120)),
                ('publish_display_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('reading_time', models.PositiveIntegerField(default=0, help_text='Auto-computed (minutes).')),
                ('is_sponsored', models.BooleanField(default=False, help_text="Shows a 'Partner Content' disclosure band and marks outbound links rel=sponsored.")),
                ('body', wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('canonical_url', models.URLField(blank=True)),
                ('noindex', models.BooleanField(default=False)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('related_articles', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Manual override; otherwise auto by tag/category.', related_name='+', to='lifestyle.articlepage')),
            ],
            options={
                'verbose_name': 'Article',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='lifestyle.articlepage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalogue.product')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='lifestyle.articlepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='articlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='lifestyle.ArticleTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='AuthorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('role', models.CharField(blank=True, help_text='Title / credentials.', max_length=120)),
                ('bio', wagtail.fields.RichTextField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('portrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Author',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='articles', to='lifestyle.authorpage'),
        ),
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(help_text='150–300 words of editorial positioning for this section.')),
                ('accent_color', models.CharField(blank=True, help_text='Optional hex accent, e.g. #9A7B43.', max_length=7)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Category page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CategoryFeatured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lifestyle.articlepage')),
                ('category', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='lifestyle.categorypage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
