# Generated by Django 5.2.15 on 2026-07-11 20:29

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0003_authorindexpage_articlepage_articleproduct_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='lead_audio_url',
            field=models.URLField(blank=True, help_text='Audio post type — embed URL (SoundCloud, etc.).'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='lead_video_url',
            field=models.URLField(blank=True, help_text='Video post type — YouTube/Vimeo embed URL (e.g. https://www.youtube.com/embed/ID).'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='post_type',
            field=models.CharField(choices=[('standard', 'Standard Article'), ('feature', 'Long-form Feature'), ('gallery', 'Photo Gallery'), ('video', 'Video Feature'), ('audio', 'Audio / Podcast'), ('quote', 'Quote'), ('interview', 'Interview / Profile'), ('review', 'Review'), ('guide', 'Guide / How-To'), ('event', 'Event Coverage'), ('list', 'Curated List')], default='standard', help_text='Pick the kind of story — drives layout, schema and badge.', max_length=16),
        ),
        migrations.CreateModel(
            name='ArticleGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='lifestyle.articlepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
