# Generated by Django 5.2.15 on 2026-07-11 20:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0004_articlepage_lead_audio_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('pull_quote', 3), ('image', 6), ('gallery', 10), ('video', 11), ('product', 14), ('faq', 18), ('key_takeaways', 21), ('table', 22), ('divider', 23), ('inline_ad', 25)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h3', 'h4', 'hr', 'blockquote'], 'label': 'Rich text'}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('quote', 1), ('attribution', 2)]], {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alt text (required for accessibility & SEO).'}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('alt', 5), ('caption', 2), ('credit', 2)]], {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('image', 4), ('alt', 7), ('caption', 2)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('images', 9)]], {}), 11: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': 'Video (YouTube/Vimeo)', 'template': 'lifestyle/blocks/video.html'}), 12: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Oscar product ID (the number in a /catalogue/…_<id>/ URL).'}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'One-line hook.', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('product_id', 12), ('blurb', 13)]], {}), 15: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h3', 'h4', 'hr', 'blockquote']}), 16: ('wagtail.blocks.StructBlock', [[('question', 7), ('answer', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('items', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'Key takeaways', 'required': False}), 20: ('wagtail.blocks.ListBlock', (7,), {}), 21: ('wagtail.blocks.StructBlock', [[('title', 19), ('points', 20)]], {}), 22: ('wagtail.blocks.RawHTMLBlock', (), {'icon': 'table', 'label': 'Table (HTML)', 'template': 'lifestyle/blocks/table.html'}), 23: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': '— divider —', 'icon': 'horizontalrule', 'label': 'Divider', 'template': 'lifestyle/blocks/divider.html'}), 24: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('in_content', 'In-content leaderboard'), ('leaderboard_top', 'Leaderboard'), ('footer', 'Footer')]}), 25: ('wagtail.blocks.StructBlock', [[('zone', 24)]], {})}),
        ),
    ]
