# Generated by Django 5.2.15 on 2026-07-11 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_category_exclude_from_menu_category_long_description'),
        ('lifestyle', '0005_alter_articlepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredProductSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook', models.CharField(blank=True, help_text='One-line hook.', max_length=140)),
                ('advertiser', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalogue.product')),
            ],
            options={
                'verbose_name': 'Sponsored product slot',
                'ordering': ['sort_order'],
            },
        ),
    ]
