# Generated by Django 5.2.15 on 2026-07-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0006_sponsoredproductslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiseInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('budget', models.CharField(blank=True, choices=[('', '—'), ('under_5k', 'Under $5,000'), ('5_25k', '$5,000 – $25,000'), ('25_100k', '$25,000 – $100,000'), ('100k_plus', '$100,000+')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Advertise inquiry',
                'verbose_name_plural': 'Advertise inquiries',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PendingSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source', models.CharField(blank=True, help_text='Page/section it came from.', max_length=120)),
                ('consent', models.BooleanField(default=False)),
                ('synced', models.BooleanField(default=False, help_text='Pushed to Mailchimp.')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pending subscriber',
                'ordering': ['-created'],
            },
        ),
    ]
